- README.md
> [Adela]2021-07-05

- 7월1주차/mc_210706.md
> [Goody] 7월 6일 화요일 TIL

- README.md
> [아델라]2021-07-06

- README.md
성불하겠습니다...알고리즘 어려워 너무 어려워 어려워 ㅠ
> [Rano] 2021-07-07

- README.md
> [아델라] 2021-07-07

- README.md
> [Rano] 2021-07-08

- README.md
오늘자 회고 링크 달아서 올립니다. 
간간히 댓글 달아주시는 분들 너무 따뜻하고 좋네요.. 감삼다!
> [아델라] 2021-07-08

- README.md
2021-07-09 회고 기록 
공부한 내용은 상당 부분 대외비인 관계로 링크없이 키워드만..
> [아델라] 2021-07-09

- 7월1주차/mc_210709.md
* 프로그래머스에서 그리디 문제를 풀려는데 해법을 모르겠어서 동적 프로그래밍 복습을 했다.
* https://github.com/junzero741/algorithm/blob/master/IF/section10/stairs_dy.js
* https://github.com/junzero741/algorithm/blob/master/IF/section10/stone_bridge_dy.js
* HTML 태그의 기본 포맷은 <태그명 속성명="속성값"> 내용 </태그명> 이라는걸 여러번 강조했다.
* 태그의 기본 포맷만 알고 있으면 모르는 태그라도 검색해서 금방 가져다 쓸 수 있으니까!!
* 숙제를 너무 잘해와서 내가 처음 HTML,CSS 를 배울 때는 어땠나.. 하고 돌아보게 된다.
* 필터 기능 추가를 위해 쿼리 스트링 사용법을 학습했다.
* `localhost:3000/주소?state=[open|close]&milestone=blabla&...`  이런 식으로 쓴다.
* 재밌는건, `<Route>` 태그에서 `component` 속성으로 컴포넌트를 그리면 안되고, `render` 속성으로 그려줘야 컴포넌트의 props에서 주소창의 ? 뒤의 쿼리스트링을 가져올 수 있다.
* 벨로퍼트님 강의에서 리덕스 미들웨어인 redux-thunk 학습
> [Goody] 7월 9일 금요일 TIL

- README.md
> [Rano] 2021-07-12

- README.md
오늘 왠지 밤에 공부 하나도 안할 것 같아서 이른 회고 올림다
> [아델라]2021-07-13

- README.md
> 아구몬을 만들고 싶었지만..
- (세로) 아(텀)구몬
<br/>
- 몬아구
<br/>
- 몬주나미구 ("아" 깔림)
<br/>
- **_아구찜_**
---
가로로 정렬!! 안해주는 "몬" 나빴다요..
`아구찜` 먹고 싶은 하루였슴다
다들 고생하셨어요 오늘도 😆
[Rano's Miracle Coding 🦖](https://github.com/GleamingStar/miracle-coding/tree/Rano)
> [Rano] 2021-07-14

- TIL/TIL_210714.md
| 날짜 | 링크         |
| ---- | ------------ |
| 0714 | [바로가기](https://github.com/GleamingStar/miracle-coding/blob/eamon/TIL/TIL_210714.md) |
> [이어몬]210714_TIL

- README.md
> [Adela] 2021-07-15

- README.md
이번주도 다들 고생하셨습니다!
라노의 미라클 코딩은.. 잠시 쉬어가겠지만 다시 온다면 반겨주세요 😄
글도 가끔 올릴게요!! 약간 블로그 스터디 느낌으로! (그래도 되죠..?)
https://user-images.githubusercontent.com/33610315/125979496-69bd35bf-ab68-4ed9-8ec7-364d4c34c9cf.mov
[Rano's Miracle Coding 🦖](https://github.com/GleamingStar/miracle-coding/tree/Rano)
> [Rano] 2021-07-16

- README.md
2주차 마지막 회고까지! 다들 고생했슴다! 좋은 주말 보내시길 🙏
> [Adela] 2021-07-16

- 7월2주차/mc_210719.md
* 문자열 제어 문제들을 풀었다.
* 정규표현식 -> replace() , sort(), localeComapre(), slice() 를 활용했다.
* commit: https://github.com/junzero741/algorithm/tree/master/PAI/string
* 태그 중첩과 엘리먼트 정렬에 대해서 강의했다.
* 엘리먼트를 정렬할 땐 정렬하고자 하는 엘리먼트에 정렬 스타일(flex, center)를 주는 것이 아니라, 정렬의 기준이 되는 컨테이너에 정렬 스타일을 주는 것이다. 정렬의 기준이 되는 태그에!
* 내가 html 작업을 할 땐 별 생각없이 정렬이 되는 부분에다가 별 생각없이 정렬값을 줬었는데, 누군가를 가르치면서 좀 더 지식을 정돈할 수 있게 되는 것 같다.
* 요즘 웹 페이지를 이용하는 유저들은 대부분 모바일 환경에서 웹 페이지를 보는데, 지금까지는 이를 전혀 고려하지 않은 개발을 했던 것 같다.
* 그래서 반응형 웹에 대한 공부를 할 필요성을 느꼈다.
* 삼성 sds 사이트에서 제공하는 반응형 웹 문서를 읽었다.
* 다가오는 프로젝트에 적용해 봐야겠다.
* https://www.samsungsds.com/kr/insights/Responsive_web_1.html
* https://www.samsungsds.com/kr/insights/Responsive-Web-2.html
> [Goody] 0719 TIL

- README.md
- TIL/TIL_210719.md
| 날짜 | 링크         |
| ---- | ------------ |
| 0719 | [바로가기](https://github.com/GleamingStar/miracle-coding/blob/eamon/TIL/TIL_210719.md) |
> [eamon]21-07-19 TIL

- README.md
> [아델라] 2021-07-19

- README.md
> [아델라] 2021-07-20

- README.md
> [아델라] 2021-07-21

- README.md
> [아델라] 2021-07-22

- README.md
> [Adela] 2021-07-26

- 7월4주차/mc_210726.md
* 배열 파티션문제와 O(N) 시간복잡도로 배열 내 원소들끼리의 곱을 구하는 문제를 풀었다.
* 배열 파티션 : https://github.com/junzero741/algorithm/blob/master/PAI/array/Array_Partition_I_561.js
* 자신 제외한 배열 내 원소끼리의 곱 : https://github.com/junzero741/algorithm/blob/master/PAI/array/Product_of_Array_Except_Self_238.js
* 아직까지는 문제를 읽는 눈이 안뜨인 느낌.. 언제쯤 그 느낌이 빡 올까??
* 마일스톤 페이지 진입이 안되는 버그가 있어서 && 연산자로 간단하게 수정했다.
* 기왕 오랜만에 이슈 트래커 손댄 김에 미루고 미뤄왔던 필터 기능을 추가했다. 예전엔 어떻게 만들지 1도 감이 안왔는데 오랜만에 했더니 어찌저찌 구현해버렸다.. 대박사건~
* ![이슈필터링](https://user-images.githubusercontent.com/71166372/126979580-3de980be-03b3-4943-a271-cb0f00fac944.gif)
* 이번 스프린트에서 내가 맡은 티켓인 코딩 컨벤션 정리를 마쳐서 pending QA 보드에 넣었다.
> [Goody] 0726 TIL

- README.md
> [아델라] 2021-07-27
